### ISSUE TITLE
identification of issue lifecycles

### ISSUE THREAD

**Issue by grokspawn** [oceanc80/gh2jira#16]
moving towards the idea of being able to independently identify state mismatches between siblings, we need to be able to identify the lifecycles of each, along with an identifier for each lifecycle type.

For e.g. we could postulate a yaml file like:

```yaml
# lifecycles.yaml
lifecycles:
- name: github-issue
  status:
  - open
  - assigned
  - closed
- name: jira-agile
  status:
  - todo
  - inprogress
  - codereview
  - done
```
