### ISSUE TITLE
mapping sibling lifecycle states

### ISSUE THREAD

**Issue by grokspawn** [oceanc80/gh2jira#17]
the `lifecycles.yaml` file defines arbitrary, independent lifecycle stages.  A `lifecycle-mapping.yaml` file builds on this to provide github-dominant stage mapping in a 1:N manner.

for e.g. 

```yaml
# lifecycle-mapping.yaml
lifecycle-mapping:
- name: agile-lifecycle
  - open: [todo]
  - assigned: [inprogress, codereview]
  - closed: [done]
```
