### ISSUE TITLE
match lifecycle to project profile info

### ISSUE THREAD

**Issue by grokspawn** [oceanc80/gh2jira#18]
building on #17 we need a mechanism to capture which lifecycle mapping kind pertains to a given project
Is there value in capturing the g/j lifecycle, or enough to capture their integrated mapping across the g/j pairing?

for example:

```yaml
# projects.yaml
projects:
- description: SDK
  github:
  - project: operator-framework/operator-sdk
  - lifecycle: github-issue
  jira:
  - project: opeco
  - lifecycle: jira-agile
  - lifecycleMapping: agile-lifecycle
  tokenStore: tokens.yaml
```
